#!/bin/sh
shopt -s globstar

echo 'Checking for whitespace errors...'
grep '\s$' **/*.{cc,h} && exit 1
pcregrep -M '\n\n\Z' **/*.{cc,h} && exit 1

echo 'Checking for too long lines...'
grep '^.\{81,\}$' **/*.{cc,h} && exit 1

echo 'Checking for lowercase hex literals...'
grep '[0\\]x[0-9]*[a-f][0-9]*' **/*.{cc,h} && exit 1

echo 'Checking for typedef...'
grep 'typedef' **/*.{cc,h} && exit 1

echo 'Checking for "length"...'
grep 'length' **/*.{cc,h} | grep -v run_length && ( echo 'Use "size" instead.'; exit 1 )

echo 'Checking for iostream outside logger...'
grep 'iostream' **/*.{cc,h} | grep -v logger && exit 1

echo 'Checking for sloppy exceptions...'
grep 'throw std' **/*.cc|grep -v logic_error

echo 'Checking for nonstatic constructs....'
grep '^[A-Z0-9a-z:<>_]\{1,\} [^:]*[(;]' **/*.cc \
    | grep -v 'using namespace' \
    | grep -v 'int main' \
    | grep -v 'compat/' \
    | grep -v static

exit 0
